### PR TITLE
Fix bug where variables come as map[interface{}]

### LINKED ISSUE #133: Mappings in variables don't seem to work
### Context
when two configs are merged, mappings variables aren't always properly merged

### To reproduce
try to load two files from a directory - `apid -c /tmp/dir/`

#### `/tmp/dir/f1.yml`:
```yaml
variables:
  mapping1:
    var1: True
    var2: '123'
transactions:
- id: "1234"
  steps:
  - id: 'non-empty'
    request:
      method: GET
      endpoint: "https://google.com/{{ var.mapping1.var2 }}"
      body: ""
```

#### `/tmp/dir/f2.yml`
```yaml
variables:
  mapping1:
    var1: 123
    var4: '4'
    var5: '5'
transactions:
- id: a
  steps:
  - id: '1'
    request:
      method: GET
      endpoint: "https://google.com"
      body: ""
```

the values inside `mapping1` aren't properly merged 

### Expected behavior
everything works

### Observed behavior
```
1234:
    FAIL non-empty

         request: GET https://google.com/ 
         errors:
             prepare:
                interpolating step endpoint: var.mapping1.var2: can't deal with this type map[interface {}]interface {}
            
a:
    OK   1
successful transactions: 1/2
failed transactions:     1/2
```

### Output of `apid version`
`APId 0.1.3`

### PR DESCRIPTION
**Pull request by dimitarvdimitrov**
## Description

Resolves #133 

### Type of change

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] I have performed a self-review of my own code
- [x] Go code is formatted with `gofmt`
- [x] I have made corresponding changes to the docs in `site/content/docs` and in the `README`
- [x] I have added tests (unit and/or end-to-end) that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published (in downstream modules)

### CODE REVIEW

File: common/variables/variables.go [hunk 1]
```diff
@@ -118,6 +119,33 @@ func mergeMaps(this, other map[string]interface{}) map[string]interface{} {
 	return this
 }
 
+// tryToStringMap returns val as map[string]interface{} and true if val is easily convertible to that.
+// It returns nil and false if it is easily convertible.
```
Comment (iv-p) [inline common/variables/variables.go]: 'not easily'
